version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: vue-hardcoded-with-resources
    path: ""
    text-resources:
      - path: "*.vue"
        format: vue-hardcoded
